version: "3"
services:
  web:
    container_name: ucimlrepo-web
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - 3000:3000
  db:
      container_name: ucimlrepo-db
      environment:
        - MYSQL_DATABASE=mlrepo
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_HOST=%
      build:
        context: ./db
        dockerfile: Dockerfile
      ports:
        - 7200:3306

  nginx:
      container_name: ucimlrepo-nginx
      build:
        context: ./nginx
        dockerfile: Dockerfile
        args:
          ENV: dev
      depends_on:
        - web
      ports:
        - 80:80
        - 443:443
